- name: Launch EC2 instances
  hosts: localhost
  vars:
    ami_image: ami-010aff33ed5991201
    security_group_id: sg-0eed0d7ed0916d197
    vpc_subnet_id: subnet-7e757c16
    instance_type: t2.micro
    instance_key: id_rsa
  tasks:
    
    - name: Launch EC2 instance for Kubernetes master
      amazon.aws.ec2:
        key_name: "{{ instance_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_image }}"
        wait: yes
        group_id: "{{ security_group_id }}"
        count: 1
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: 
          Name: master
        
    - name: Launch EC2 instance for Kubernetes slave
      amazon.aws.ec2:
        key_name: "{{ instance_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_image }}"
        wait: yes
        group_id: "{{ security_group_id }}"
        count: 2
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: 
          Name: slave