- name: Launch EC2 instances
  hosts: localhost
  vars:
    ami_image: ami-0d5eff06f840b45e9
    security_group: launch-wizard-1
    vpc_subnet_id: subnet-09204307
    instance_type: t2.micro
    instance_key: virginia_key
    aws_region: us-east-1
    price: "0.0036"
  tasks:
    
    - name: Launch EC2 instance for Kubernetes master
      amazon.aws.ec2:
        spot_price: "{{ price }}"
        key_name: "{{ instance_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_image }}"
        wait: yes
        group: "{{ security_group }}"
        count: 1
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        region: "{{ aws_region }}"
        assign_public_ip: yes
        instance_initiated_shutdown_behavior: terminate
        instance_tags: 
          Name: master
        
    - name: Launch EC2 instance for Kubernetes slave
      amazon.aws.ec2:
        spot_price: "{{ price }}"
        key_name: "{{ instance_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_image }}"
        wait: yes
        group: "{{ security_group }}"
        count: 2
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        region: "{{ aws_region }}"
        assign_public_ip: yes
        instance_initiated_shutdown_behavior: terminate
        instance_tags: 
          Name: slave