- name: Configuring Kubernetes
  hosts:
    - tag_Name_master
    - tag_Name_slave
  tasks:

    - name: Configure Kubernetes Repository
      copy:
        src: kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo

    - name: Install Kubernetes
      yum:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Start kubelet service
      service:
        name: kubelet
        state: started
        enabled: yes

    - name: Install iprooute-tc
      yum:
        name: iproute-tc
        state: present

    - name: Copying daemon file
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json

    - name: Restart docker
      service:
        name: docker
        state: restarted

    - name: Copying Kubernetes config file
      copy:
        src: k8s.conf
        dest: /etc/sysctl.d/k8s.conf

    - name: Reloading sysctl
      shell: sysctl --system


- name: Configuring Kubernetes Master
  hosts: tag_Name_master
  tasks:

    - name: Pulling images for kubernetes
      shell: kubeadm config images pull

    - name: Initializing kubeadm
      shell: kubeadm init --pod-network-cidr=10.240.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
      ignore_errors: true

    - name: Creating directory
      file:
        path: /root/.kube
        state: directory

    - name: Copying config file
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: root
        group: root

    - name: Getting token
      shell: kubeadm token create --print-join-command
      register: token

- name: Configuring Kubernetes Slave
  hosts: tag_Name_slave
  tasks:

    - name: Connecting slave with master
      shell: "{{ token.stdout }}"